# This notebook will serve as a way to implement character generation LSTM and other implementation

In [1]:
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch.nn as nn
import re
import numpy as np

In [2]:
with open("/kaggle/input/multiple/clean_regroup.txt", "r", encoding="utf-8", errors="replace") as f:
    corpus = f.read()

# Data preparation

## We need first to create a mapping of each character for encoding

In [3]:
print(f"Length of the corpus characters : {len(corpus)}")

Length of the corpus characters : 991402


In [4]:
chars_sort = sorted(set(corpus))

#Encode
char2int = {ch: i for i, ch in enumerate(chars_sort)}
print(char2int,"\n")

# Decode
int2char = {i: ch for ch, i in char2int.items()}
print(int2char)

nb_char = len(int2char)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '%': 4, '&': 5, "'": 6, '+': 7, ',': 8, '-': 9, '.': 10, '/': 11, '0': 12, '1': 13, '2': 14, '3': 15, '4': 16, '5': 17, '6': 18, '7': 19, '8': 20, '9': 21, ':': 22, ';': 23, '<': 24, '>': 25, '?': 26, 'A': 27, 'B': 28, 'C': 29, 'D': 30, 'E': 31, 'F': 32, 'G': 33, 'H': 34, 'I': 35, 'J': 36, 'K': 37, 'L': 38, 'M': 39, 'N': 40, 'O': 41, 'P': 42, 'Q': 43, 'R': 44, 'S': 45, 'T': 46, 'U': 47, 'V': 48, 'W': 49, 'X': 50, 'Y': 51, 'Z': 52, 'a': 53, 'b': 54, 'c': 55, 'd': 56, 'e': 57, 'f': 58, 'g': 59, 'h': 60, 'i': 61, 'j': 62, 'k': 63, 'l': 64, 'm': 65, 'n': 66, 'o': 67, 'p': 68, 'q': 69, 'r': 70, 's': 71, 't': 72, 'u': 73, 'v': 74, 'w': 75, 'x': 76, 'y': 77, 'z': 78, '§': 79, 'À': 80, 'Ç': 81, 'É': 82, 'Ê': 83, 'Î': 84, 'Ô': 85, 'Ö': 86, 'Ü': 87, 'à': 88, 'á': 89, 'â': 90, 'ã': 91, 'ä': 92, 'æ': 93, 'ç': 94, 'è': 95, 'é': 96, 'ê': 97, 'ë': 98, 'í': 99, 'î': 100, 'ï': 101, 'ñ': 102, 'ô': 103, 'ö': 104, 'ù': 105, 'û': 106, 'ü': 107, 'Ā': 108, 'ā': 109, 'ğ': 110

In [5]:
corpus_encoded = np.array([char2int[ch] for ch in corpus])
corpus_encoded

array([24, 28, 31, ..., 30, 25,  0])

## Creation of the dataset

To increase the randomness during the training :

For each epoch the entire corpus will have a random specific offset value in order that the model during training doesn't see the exact same text during X epochs.

In [6]:
class CharDataset(Dataset) :
    def __init__(self, text, length_seq) :
        self.text = text
        self.length_seq = length_seq
        self.max_start = len(text) - length_seq - 1
        self.offset = 0

        # ensure text is torch tensor
        if not torch.is_tensor(text):
            text = torch.tensor(text, dtype=torch.long)
        self.text = text
        
    def set_offset(self, offset) :
        self.offset = offset
        
    def __len__(self) :
        return self.max_start

    def __getitem__(self, i) :
        s = (i + self.offset) % self.max_start
        x = self.text[s:s+self.length_seq]
        y = self.text[s+1:s+self.length_seq+1]
        return x, y

In [7]:
train_size = int(len(corpus_encoded)*0.9)
train_encoded = torch.tensor(corpus_encoded[:train_size], dtype=torch.long)
test_encoded = torch.tensor(corpus_encoded[train_size:], dtype=torch.long)

In [8]:
seq_length = 250
train_dataset = CharDataset(train_encoded, length_seq= seq_length)
test_dataset = CharDataset(test_encoded, length_seq= seq_length)

In [9]:
print(train_dataset[0][0])
print("".join([int2char[i] for i in train_encoded[:seq_length].numpy()]))

tensor([24, 28, 31, 33, 35, 40, 40, 35, 40, 33, 25,  0, 24, 29, 41, 47, 42, 38,
        31, 46, 25,  0, 36,  6, 53, 61, 65, 57,  1, 68, 53, 71,  1, 64, 57, 71,
         1, 54, 57, 73, 70, 57, 72, 72, 57, 71,  1, 56, 67, 66, 55,  1, 58, 53,
        73, 72,  1, 69, 73,  6, 55, 57, 71,  1, 68, 67, 73, 58, 58, 61, 53, 71,
        71, 57, 71,  1, 65,  6, 57, 66, 72, 57, 66, 56, 57, 66, 72,  0, 51,  1,
        53,  1, 69, 73,  6, 56, 53, 66, 71,  1, 27, 64, 53, 56, 56, 61, 66,  1,
        69, 73, 57,  1, 72,  6, 57, 66,  1, 74, 57, 70, 70, 53, 71,  1, 73, 66,
        57,  1, 63, 61, 58, 58, 57, 70,  1, 71, 73, 70,  1, 73, 66,  1, 65, 57,
        66, 56, 61, 53, 66, 72,  0, 51,  1, 53,  1, 68, 64, 73, 71,  1, 56,  6,
        70, 57, 71, 68, 57, 55, 72,  1, 57, 66, 72, 70, 57,  1, 64, 57, 71,  1,
        56, 53, 70, 67, 66, 66, 57, 71,  8,  1, 64, 57, 71,  1, 68, 57, 72, 61,
        72, 57, 71,  1, 56,  6, 13, 18,  1, 68, 61, 59, 57, 71,  0, 40, 67, 70,
        65, 53, 64,  1, 69, 73, 57,  1, 

## Creation of Dataloader and co

In [10]:
batch_size = 256

train_dl = DataLoader(train_dataset, batch_size=batch_size, pin_memory=True, pin_memory_device="cuda:0", 
                        num_workers=4, prefetch_factor=4, shuffle=False, drop_last=True) #Shuffle False because we need the RNN to use previous sequences data to predict next one
test_dl = DataLoader(test_dataset, batch_size=batch_size, pin_memory=True, pin_memory_device="cuda:0", 
                       num_workers=2, prefetch_factor=2, shuffle=False, drop_last=True)

### Check the good dataloading and offset validity

In [11]:
for i in train_dl :
    print(i[0])
    break

tensor([[24, 28, 31,  ..., 66,  0, 45],
        [28, 31, 33,  ...,  0, 45, 57],
        [31, 33, 35,  ..., 45, 57,  1],
        ...,
        [70, 57, 66,  ..., 57,  1, 73],
        [57, 66, 66,  ...,  1, 73, 66],
        [66, 66, 57,  ..., 73, 66, 57]])


In [12]:
train_dataset.set_offset(1)
next(iter(train_dl))

[tensor([[28, 31, 33,  ...,  0, 45, 57],
         [31, 33, 35,  ..., 45, 57,  1],
         [33, 35, 40,  ..., 57,  1, 68],
         ...,
         [57, 66, 66,  ...,  1, 73, 66],
         [66, 66, 57,  ..., 73, 66, 57],
         [66, 57, 66,  ..., 66, 57,  1]]),
 tensor([[31, 33, 35,  ..., 45, 57,  1],
         [33, 35, 40,  ..., 57,  1, 68],
         [35, 40, 40,  ...,  1, 68, 70],
         ...,
         [66, 66, 57,  ..., 73, 66, 57],
         [66, 57, 66,  ..., 66, 57,  1],
         [57, 66, 72,  ..., 57,  1, 55]])]

In [13]:
len(train_dl)

3484

## Models

### Training part

In [14]:
embedding_dim = 64
hidden_size = 236
vocab_size = len(char2int)
num_epoch = 50

In [15]:
class CharRNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size, num_layers=1):
        super(CharRNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(input_size = embedding_dim, 
                            hidden_size = hidden_size, 
                            num_layers = num_layers, 
                            batch_first=True, dropout = 0.15)
        self.drop = nn.Dropout(p=0.15)
        self.ln = nn.LayerNorm(hidden_size)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden):
        x = self.embedding(x)              # (batch, seq, hidden_size)
        x = self.drop(x)
        out, hidden = self.lstm(x, hidden)
        out = self.ln(out)
        out = self.drop(out)
        logits = self.fc(out)                  
        return logits, hidden

    def init_hidden(self, batch_size, device):
#        return torch.zeros(self.num_layers, batch_size, self.hidden_size)
        self.device = device
        h0 = torch.randn(self.num_layers, batch_size, self.hidden_size, device = device)
        c0 = torch.randn(self.num_layers, batch_size, self.hidden_size, device = device)
        return (h0,c0)

In [16]:
device1 = torch.device("cuda:0")
device2 = torch.device("cuda:1")

In [18]:
nb_step_train = len(train_dl)
nb_step_test = len(test_dl)

model = CharRNN(vocab_size, embedding_dim, hidden_size, num_layers=2)   

model.to(device1)

loss_fn = nn.CrossEntropyLoss()

opti = torch.optim.AdamW(model.parameters(), lr=0.003, weight_decay=1e-4)
sched_warm = torch.optim.lr_scheduler.LinearLR(opti, start_factor=0.2, end_factor=1.0, total_iters=nb_step_train)
sched_post = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(opti, T_0=len(train_dl)*10, T_mult=2, eta_min=0.00025) #1 epoch => 2 => 4 => 8

In [ ]:
list_offset = []
l_tot = []

#Early stopping
early_stopping_count = 0
patience = 5

best_val = float("inf")

scaler = torch.amp.GradScaler()

hid = model.init_hidden(batch_size, device1)

hid_ = model.init_hidden(batch_size, device1)

for epoch in range(num_epoch) :
    
    offset = np.random.randint(0, seq_length-1) #Set the offset
    list_offset.append(offset) #Keep in memory

    #Offset the datas
    train_dataset.set_offset(offset); test_dataset.set_offset(offset)

    model.train();
    hid = tuple(h.zero_() for h in hid);

    #Create loss per epoch
    l_train = 0.0
    l_test = 0.0
    
    for X,Y in iter(train_dl) :
        X = X.to(device1); Y= Y.to(device1)
        opti.zero_grad(set_to_none=True)
        
        #Computation of model
        hid = tuple(h.detach() for h in hid)
        
        with torch.amp.autocast(device_type="cuda:0"):
            pred, hid = model(X, hid)
            loss = loss_fn(pred.view(-1, vocab_size), Y.view(-1))

        scaler.scale(loss).backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.25)
        scaler.step(opti); scaler.update()
        l_train += loss.detach()

        #Scheduler part
        #Warm start
        
        if sched_post.T_cur == 0 and epoch > 1:  #After warm restart decrease the max learning rate
            sched_post.base_lrs[0] = sched_post.base_lrs[0] * 0.8
            sched_post.eta_min = sched_post.eta_min * 1.5
            print(f"Decrease {sched_post.base_lrs[0]}, {sched_post.eta_min}")

        step_scheduler = sched_warm if epoch == 0 else sched_post
        step_scheduler.step()

    #Test data part
    
    model.eval()
    
    
    with torch.inference_mode():
        hid_ = tuple(h.zero_() for h in hid_);
        with torch.amp.autocast("cuda"):
            for X,Y in iter(test_dl) : 
                X = X.to(device1); Y= Y.to(device1)
                hid_ = tuple(h.detach() for h in hid_)
                            
                pred, hid_ = model(X, hid_)
                loss = loss_fn(pred.view(-1, vocab_size), Y.view(-1))
                l_test += loss.detach()

        print(epoch,np.exp(l_test.item()/nb_step_test),"\n")
     
        #Record the loss of the epoch
        l_tot.append(l_test.item()); 

        if l_test < best_val :
            best_val = l_test.item()
            early_stopping_count = 0
            torch.save({
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": opti.state_dict(),
                "scheduler_state_dict": sched_post.state_dict(),
                "val_loss": l_test,
            }, "model1")
        
        elif l_test >= best_val :
            early_stopping_count += 1

#        if early_stopping_count == patience :
#            print("Early Stopping")
#            break 

print(f"Liste of offset used : {list_offset}")

0 5.57882494166434 

1 4.7246994419502695 

2 4.651461534493395 

3 4.5934337757106976 

4 4.537521625967685 

5 4.496199531770168 

6 4.460959413710131 

7 4.447629412567331 

8 4.4185441981626274 

9 4.4032537780760075 

10 4.395073462314534 

Decrease 0.0024000000000000002, 0.000375
11 4.446694163411667 

12 4.37945082796318 

13 4.354019228772756 

14 4.329612205225856 

15 4.342529444388261 

16 4.28545038115904 

17 4.2963101788355775 

18 4.2781491032107475 

19 4.259604072086402 

20 4.242853876877804 

21 4.208143937148287 

22 4.211561492037195 

23 4.189398883983312 

24 4.1806241738301635 

25 4.173477734946584 

26 4.174147606831554 

27 4.170152407023449 

28 4.167396393774512 

29 4.165597168678642 

30 4.16430768608162 

Decrease 0.0019200000000000003, 0.0005625000000000001
31 4.2029550161987075 

32 4.167296892342704 

33 4.155969945065971 

34 4.1761202282810155 

35 4.171708206514356 

36 4.164942498918957 

37 4.128566152790262 

38 4.12076452652224 



4.2059280975299735 

In [ ]:
torch.save(model.state_dict(), "modele.pth")