# This notebook will serve as a way to train character generation LSTM 

This code is used on Kaggle

In [ ]:
import numpy as np
import pickle

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [2]:
with open("/kaggle/input/rnn-input/encoding_map.pkl", "rb") as f:
    mapping = pickle.load(f)

# Data preparation

In [3]:
# Decode
int2char = {i: ch for ch, i in mapping.items()}
print(int2char)

nb_char = len(int2char)

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '%', 5: '&', 6: "'", 7: '+', 8: ',', 9: '-', 10: '.', 11: '/', 12: '0', 13: '1', 14: '2', 15: '3', 16: '4', 17: '5', 18: '6', 19: '7', 20: '8', 21: '9', 22: ':', 23: ';', 24: '<', 25: '>', 26: '?', 27: 'A', 28: 'B', 29: 'C', 30: 'D', 31: 'E', 32: 'F', 33: 'G', 34: 'H', 35: 'I', 36: 'J', 37: 'K', 38: 'L', 39: 'M', 40: 'N', 41: 'O', 42: 'P', 43: 'Q', 44: 'R', 45: 'S', 46: 'T', 47: 'U', 48: 'V', 49: 'W', 50: 'X', 51: 'Y', 52: 'Z', 53: 'a', 54: 'b', 55: 'c', 56: 'd', 57: 'e', 58: 'f', 59: 'g', 60: 'h', 61: 'i', 62: 'j', 63: 'k', 64: 'l', 65: 'm', 66: 'n', 67: 'o', 68: 'p', 69: 'q', 70: 'r', 71: 's', 72: 't', 73: 'u', 74: 'v', 75: 'w', 76: 'x', 77: 'y', 78: 'z', 79: '§', 80: 'À', 81: 'Ç', 82: 'É', 83: 'Ê', 84: 'Î', 85: 'Ô', 86: 'Ö', 87: 'Ü', 88: 'à', 89: 'á', 90: 'â', 91: 'ã', 92: 'ä', 93: 'æ', 94: 'ç', 95: 'è', 96: 'é', 97: 'ê', 98: 'ë', 99: 'í', 100: 'î', 101: 'ï', 102: 'ñ', 103: 'ô', 104: 'ö', 105: 'ù', 106: 'û', 107: 'ü', 108: 'Ā', 109: 'ā', 110: 'ğ'

## Creation of the dataset

To increase the randomness during the training :

For each epoch the entire corpus will have a random specific offset value in order that the model during training doesn't see the exact same text during X epochs.

In [4]:
class CharDataset(Dataset) :
    def __init__(self,text,length_seq) :
        self.text = text
        self.length_seq = length_seq
        self.max_start = len(self.text) - length_seq - 1
        self.offset = 0
        
    def set_offset(self, offset) :
        self.offset = offset
        
    def __len__(self) :
        return self.max_start

    def __getitem__(self, i) :
        s = (i + self.offset) % self.max_start
        x = torch.from_numpy(self.text[s:s+self.length_seq])
        y = torch.from_numpy(self.text[s+1:s+self.length_seq+1])
        return x, y

In [5]:
seq_length = 250
dataset_ = np.load("/kaggle/input/rnn-input/corpora_encoded.npy","r")
len_train = int(len(dataset_)*0.9)
train = dataset_[:len_train]
test = dataset_[len_train:]

In [6]:
train_ds = CharDataset(train,length_seq=250)
test_ds = CharDataset(test,length_seq=250)

In [7]:
print(train_ds[0][0])
print("".join([int2char[i] for i in train_ds[0][0][:seq_length].numpy()]))

tensor([24, 28, 31, 33, 35, 40, 40, 35, 40, 33, 25,  0, 24, 44, 31, 32, 44, 27,
        35, 40, 25,  0, 41, 66,  1, 74, 61, 72,  1, 71, 67, 73, 71,  1, 72, 57,
        66, 71, 61, 67, 66,  1, 57, 72,  1, 55,  6, 57, 71, 72,  1, 72, 67, 73,
        72,  1, 64,  6, 72, 57, 65, 68, 71,  1, 71, 67, 65, 54, 70, 57,  1, 57,
        72,  1, 62,  6, 65,  6, 57, 66,  1, 58, 67, 73, 71,  1, 56, 53, 66, 71,
         1, 64,  6, 58, 67, 66, 56,  8,  1, 62,  6, 71, 73, 61, 71,  1, 56, 53,
        66, 71,  1, 65, 67, 66,  1, 96, 64, 96, 65, 57, 66, 72,  8,  1, 57, 60,
         0, 36,  6, 71, 73, 61, 71,  1, 56, 53, 66, 71,  1, 65, 67, 66,  1, 96,
        64, 96, 65, 57, 66, 72,  1, 57, 60,  8,  1, 62,  6, 71, 73, 61, 71,  1,
        56, 53, 66, 71,  1, 65, 67, 66,  1, 96, 64, 96, 65, 57, 66, 72,  0, 41,
        66,  1, 74, 61, 72,  1, 71, 67, 73, 71,  1, 72, 57, 66, 71, 61, 67, 66,
         1, 57, 72,  1, 55,  6, 57, 71, 72,  1, 72, 67, 73, 72,  1, 64,  6, 72,
        57, 65, 68, 71,  1, 71, 67, 65, 

/tmp/ipykernel_36/303235149.py:16: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:203.)
  x = torch.from_numpy(self.text[s:s+self.length_seq])


## Creation of Dataloader and co

In [8]:
batch_size = 512

train_dl = DataLoader(train_ds, batch_size=batch_size, pin_memory=True, pin_memory_device="cuda:0", 
                        num_workers=4, prefetch_factor=4, shuffle=False, drop_last=True) #Shuffle False because we need the RNN to use previous sequences data to predict next one
test_dl = DataLoader(test_ds, batch_size=batch_size, pin_memory=True, pin_memory_device="cuda:0", 
                       num_workers=2, prefetch_factor=2, shuffle=False, drop_last=True)

### Check the good dataloading and offset validity

In [9]:
for i in train_dl :
    print(i[0])
    break

tensor([[24, 28, 31,  ...,  1, 64,  6],
        [28, 31, 33,  ..., 64,  6, 58],
        [31, 33, 35,  ...,  6, 58, 67],
        ...,
        [61, 67, 66,  ..., 64, 96, 65],
        [67, 66,  1,  ..., 96, 65, 57],
        [66,  1, 57,  ..., 65, 57, 66]], dtype=torch.int32)


In [10]:
train_ds.set_offset(1)
next(iter(train_dl))

[tensor([[28, 31, 33,  ..., 64,  6, 58],
         [31, 33, 35,  ...,  6, 58, 67],
         [33, 35, 40,  ..., 58, 67, 66],
         ...,
         [67, 66,  1,  ..., 96, 65, 57],
         [66,  1, 57,  ..., 65, 57, 66],
         [ 1, 57, 72,  ..., 57, 66, 72]], dtype=torch.int32),
 tensor([[31, 33, 35,  ...,  6, 58, 67],
         [33, 35, 40,  ..., 58, 67, 66],
         [35, 40, 40,  ..., 67, 66, 56],
         ...,
         [66,  1, 57,  ..., 65, 57, 66],
         [ 1, 57, 72,  ..., 57, 66, 72],
         [57, 72,  1,  ..., 66, 72,  8]], dtype=torch.int32)]

In [11]:
len(train_dl)

1742

## Models

### Training part

In [12]:
class CharLSTM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size, num_layers=1):
        super(CharLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(input_size = embedding_dim, 
                            hidden_size = hidden_size, 
                            num_layers = num_layers, 
                            batch_first=True, dropout = 0.15)
        self.drop = nn.Dropout(p=0.15)
        self.ln = nn.LayerNorm(hidden_size)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden):
        x = self.embedding(x)              # (batch, seq, hidden_size)
        x = self.drop(x)
        out, hidden = self.lstm(x, hidden)
        out = self.ln(out)
        out = self.drop(out)
        logits = self.fc(out)                  
        return logits, hidden

    def init_hidden(self, batch_size, device):
#        return torch.zeros(self.num_layers, batch_size, self.hidden_size)
        self.device = device
        h0 = torch.randn(self.num_layers, batch_size, self.hidden_size, device = device)
        c0 = torch.randn(self.num_layers, batch_size, self.hidden_size, device = device)
        return (h0,c0)

In [13]:
device1 = torch.device("cuda:0")
device2 = torch.device("cuda:1")

In [14]:
embedding_dim = 64
hidden_size = 236
vocab_size = len(mapping)
num_epoch = 50

nb_step_train = len(train_dl)
nb_step_test = len(test_dl)

model = CharLSTM(vocab_size, embedding_dim, hidden_size, num_layers=3)   

model.to(device1)

loss_fn = nn.CrossEntropyLoss()

opti = torch.optim.AdamW(model.parameters(), lr=0.0015, weight_decay=1e-3)
sched_warm = torch.optim.lr_scheduler.LinearLR(opti, start_factor=0.2, end_factor=1.0, total_iters=nb_step_train*4)
sched_post = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(opti, T_0=nb_step_train*10, T_mult=2, eta_min=0.0001) #1 epoch => 2 => 4 => 8

In [15]:
list_offset = []
l_tot = []

#Early stopping
early_stopping_count = 0
patience = 5

best_val = float("inf")

scaler = torch.amp.GradScaler()

hid = model.init_hidden(batch_size, device1)

hid_ = model.init_hidden(batch_size, device1)

for epoch in range(num_epoch) :
    
    offset = np.random.randint(0, seq_length-1) #Set the offset
    list_offset.append(offset) #Keep in memory

    #Offset the datas
    train_ds.set_offset(offset); test_ds.set_offset(offset)

    model.train();
    hid = tuple(h.zero_() for h in hid);

    #Create loss per epoch
    l_train = 0.0
    l_test = 0.0
    
    for X,Y in iter(train_dl) :
        X = X.to(device1); Y= Y.to(device1, dtype=torch.long)
        opti.zero_grad(set_to_none=True)
        
        #Computation of model
        hid = tuple(h.detach() for h in hid)
        
        with torch.amp.autocast(device_type="cuda:0"):
            pred, hid = model(X, hid)
            loss = loss_fn(pred.view(-1, vocab_size), Y.view(-1))

        scaler.scale(loss).backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.25)
        scaler.step(opti); scaler.update()
        l_train += loss.detach()

        #Scheduler part
        #Warm start
        
        if sched_post.T_cur == 0 and epoch > 4:  #After warm restart decrease the max learning rate
            sched_post.base_lrs[0] = sched_post.base_lrs[0] * 0.8
            sched_post.eta_min = sched_post.eta_min * 1.5
            print(f"Decrease {sched_post.base_lrs[0]}, {sched_post.eta_min}")

        step_scheduler = sched_warm if epoch < 4 else sched_post
        step_scheduler.step()

    #Test data part
    
    model.eval()
    
    
    with torch.inference_mode():
        hid_ = tuple(h.zero_() for h in hid_);
        with torch.amp.autocast("cuda"):
            for X,Y in iter(test_dl) : 
                X = X.to(device1); Y= Y.to(device1, dtype=torch.long)
                hid_ = tuple(h.detach() for h in hid_)
                            
                pred, hid_ = model(X, hid_)
                loss = loss_fn(pred.view(-1, vocab_size), Y.view(-1))
                l_test += loss.detach()

        print(epoch,np.exp(l_test.item()/nb_step_test),"\n")
     
        #Record the loss of the epoch
        l_tot.append(l_test.item()); 

        if l_test < best_val :
            best_val = l_test.item()
            early_stopping_count = 0
            torch.save({
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": opti.state_dict(),
                "scheduler_state_dict": sched_post.state_dict(),
                "val_loss": l_test,
            }, "model1")
        
        elif l_test >= best_val :
            early_stopping_count += 1

#        if early_stopping_count == patience :
#            print("Early Stopping")
#            break 

print(f"Liste of offset used : {list_offset}")

0 7.663341441090051 

1 6.253294083083477 

2 5.5663241065232 

3 5.333978564242028 

4 4.8815871718556565 

5 4.840269456166661 

6 4.824793537420221 

7 4.74912988640084 

8 4.731708508066264 

9 4.695096154474725 

10 4.675528066928357 

11 4.66885100396625 

12 4.663565183728121 

13 4.660329063841852 

Decrease 0.0012000000000000001, 0.00015000000000000001
14 4.638517875224062 

15 4.626040324341444 

16 4.6029562940225786 

17 4.563289005446291 

18 4.5648947525428545 

19 4.5232082262068225 

20 4.507242731158819 

21 4.484045965690609 

22 4.485130908329446 

23 4.460279482521789 

24 4.450641125523652 

25 4.439137120517844 

26 4.433876497133653 

27 4.42227387333154 

28 4.414566366702491 

29 4.414249467555099 

30 4.406531559499118 

31 4.409546121798426 

32 4.403771123721459 

33 4.4076890469903285 

Decrease 0.0009600000000000001, 0.00022500000000000002
34 4.404370011534782 

35 4.384326579933416 

36 4.378660077775713 

37 4.359729672797607 

38 4.355319937093809 

39 